/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;
use std::borrow::Cow;
use std::collections::HashMap;

use hyper;
use serde_json;
use futures;
use futures::{Future, Stream};

use hyper::header::UserAgent;

use super::{configuration, Error};

pub struct TranslationApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> TranslationApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> TranslationApiClient<C> {
        TranslationApiClient {
            configuration: configuration,
        }
    }
}

pub trait TranslationApi {
    fn entries_source_translation_language_word_id_translationstarget_translation_language_get(
        &self,
        source_translation_language: &str,
        word_id: &str,
        target_translation_language: &str,
        app_id: &str,
        app_key: &str,
    ) -> Box<Future<Item = ::models::RetrieveEntry, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect> TranslationApi for TranslationApiClient<C> {
    fn entries_source_translation_language_word_id_translationstarget_translation_language_get(
        &self,
        source_translation_language: &str,
        word_id: &str,
        target_translation_language: &str,
        app_id: &str,
        app_key: &str,
    ) -> Box<Future<Item = ::models::RetrieveEntry, Error = Error<serde_json::Value>>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query_string = {
            let mut query = ::url::form_urlencoded::Serializer::new(String::new());
            query.finish()
        };
        let uri_str = format!("{}/entries/{source_translation_language}/{word_id}/translations={target_translation_language}?{}", configuration.base_path, query_string, source_translation_language=source_translation_language, word_id=word_id, target_translation_language=target_translation_language);

        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut uri: hyper::Uri = uri_str.parse().unwrap();

        let mut req = hyper::Request::new(method, uri);

        if let Some(ref user_agent) = configuration.user_agent {
            req.headers_mut()
                .set(UserAgent::new(Cow::Owned(user_agent.clone())));
        }

        {
            let mut headers = req.headers_mut();
            headers.set_raw("app_id", app_id);
            headers.set_raw("app_key", app_key);
        }

        // send request
        Box::new(
            configuration
                .client
                .request(req)
                .map_err(|e| Error::from(e))
                .and_then(|resp| {
                    let status = resp.status();
                    resp.body()
                        .concat2()
                        .and_then(move |body| Ok((status, body)))
                        .map_err(|e| Error::from(e))
                })
                .and_then(|(status, body)| {
                    if status.is_success() {
                        Ok(body)
                    } else {
                        Err(Error::from((status, &*body)))
                    }
                })
                .and_then(|body| {
                    let parsed: Result<::models::RetrieveEntry, _> = serde_json::from_slice(&body);
                    parsed.map_err(|e| Error::from(e))
                }),
        )
    }
}
