/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;
use std::borrow::Cow;
use std::collections::HashMap;

use hyper;
use serde_json;
use futures;
use futures::{Future, Stream};

use hyper::header::UserAgent;

use super::{configuration, Error};

pub struct WordlistApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> WordlistApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> WordlistApiClient<C> {
        WordlistApiClient {
            configuration: configuration,
        }
    }
}

pub trait WordlistApi {
    fn wordlist_source_lang_filters_advanced_get(
        &self,
        source_lang: &str,
        filters_advanced: &str,
        app_id: &str,
        app_key: &str,
        exclude: &str,
        exclude_senses: &str,
        exclude_prime_senses: &str,
        word_length: &str,
        prefix: &str,
        exact: bool,
        limit: &str,
        offset: &str,
    ) -> Box<Future<Item = ::models::Wordlist, Error = Error<serde_json::Value>>>;
    fn wordlist_source_lang_filters_basic_get(
        &self,
        source_lang: &str,
        filters_basic: &str,
        app_id: &str,
        app_key: &str,
        limit: &str,
        offset: &str,
    ) -> Box<Future<Item = ::models::Wordlist, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect> WordlistApi for WordlistApiClient<C> {
    fn wordlist_source_lang_filters_advanced_get(
        &self,
        source_lang: &str,
        filters_advanced: &str,
        app_id: &str,
        app_key: &str,
        exclude: &str,
        exclude_senses: &str,
        exclude_prime_senses: &str,
        word_length: &str,
        prefix: &str,
        exact: bool,
        limit: &str,
        offset: &str,
    ) -> Box<Future<Item = ::models::Wordlist, Error = Error<serde_json::Value>>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query_string = {
            let mut query = ::url::form_urlencoded::Serializer::new(String::new());
            query.append_pair("exclude", &exclude.to_string());
            query.append_pair("exclude_senses", &exclude_senses.to_string());
            query.append_pair("exclude_prime_senses", &exclude_prime_senses.to_string());
            query.append_pair("word_length", &word_length.to_string());
            query.append_pair("prefix", &prefix.to_string());
            query.append_pair("exact", &exact.to_string());
            query.append_pair("limit", &limit.to_string());
            query.append_pair("offset", &offset.to_string());
            query.finish()
        };
        let uri_str = format!(
            "{}/wordlist/{source_lang}/{filters_advanced}?{}",
            configuration.base_path,
            query_string,
            source_lang = source_lang,
            filters_advanced = filters_advanced
        );

        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut uri: hyper::Uri = uri_str.parse().unwrap();

        let mut req = hyper::Request::new(method, uri);

        if let Some(ref user_agent) = configuration.user_agent {
            req.headers_mut()
                .set(UserAgent::new(Cow::Owned(user_agent.clone())));
        }

        {
            let mut headers = req.headers_mut();
            headers.set_raw("app_id", app_id);
            headers.set_raw("app_key", app_key);
        }

        // send request
        Box::new(
            configuration
                .client
                .request(req)
                .map_err(|e| Error::from(e))
                .and_then(|resp| {
                    let status = resp.status();
                    resp.body()
                        .concat2()
                        .and_then(move |body| Ok((status, body)))
                        .map_err(|e| Error::from(e))
                })
                .and_then(|(status, body)| {
                    if status.is_success() {
                        Ok(body)
                    } else {
                        Err(Error::from((status, &*body)))
                    }
                })
                .and_then(|body| {
                    let parsed: Result<::models::Wordlist, _> = serde_json::from_slice(&body);
                    parsed.map_err(|e| Error::from(e))
                }),
        )
    }

    fn wordlist_source_lang_filters_basic_get(
        &self,
        source_lang: &str,
        filters_basic: &str,
        app_id: &str,
        app_key: &str,
        limit: &str,
        offset: &str,
    ) -> Box<Future<Item = ::models::Wordlist, Error = Error<serde_json::Value>>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query_string = {
            let mut query = ::url::form_urlencoded::Serializer::new(String::new());
            query.append_pair("limit", &limit.to_string());
            query.append_pair("offset", &offset.to_string());
            query.finish()
        };
        let uri_str = format!(
            "{}/wordlist/{source_lang}/{filters_basic}?{}",
            configuration.base_path,
            query_string,
            source_lang = source_lang,
            filters_basic = filters_basic
        );

        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut uri: hyper::Uri = uri_str.parse().unwrap();

        let mut req = hyper::Request::new(method, uri);

        if let Some(ref user_agent) = configuration.user_agent {
            req.headers_mut()
                .set(UserAgent::new(Cow::Owned(user_agent.clone())));
        }

        {
            let mut headers = req.headers_mut();
            headers.set_raw("app_id", app_id);
            headers.set_raw("app_key", app_key);
        }

        // send request
        Box::new(
            configuration
                .client
                .request(req)
                .map_err(|e| Error::from(e))
                .and_then(|resp| {
                    let status = resp.status();
                    resp.body()
                        .concat2()
                        .and_then(move |body| Ok((status, body)))
                        .map_err(|e| Error::from(e))
                })
                .and_then(|(status, body)| {
                    if status.is_success() {
                        Ok(body)
                    } else {
                        Err(Error::from((status, &*body)))
                    }
                })
                .and_then(|body| {
                    let parsed: Result<::models::Wordlist, _> = serde_json::from_slice(&body);
                    parsed.map_err(|e| Error::from(e))
                }),
        )
    }
}
