/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ArrayOfRelatedEntriesInner {
  /// A subject, discipline, or branch of knowledge particular to the Sense
  #[serde(rename = "domains")]
  domains: Option<Vec<String>>,
  /// The identifier of the word
  #[serde(rename = "id")]
  id: String,
  /// IANA language code specifying the language of the word
  #[serde(rename = "language")]
  language: Option<String>,
  /// A particular area in which the pronunciation occurs, e.g. 'Great Britain'
  #[serde(rename = "regions")]
  regions: Option<Vec<String>>,
  /// A level of language usage, typically with respect to formality. e.g. 'offensive', 'informal'
  #[serde(rename = "registers")]
  registers: Option<Vec<String>>,
  #[serde(rename = "text")]
  text: String,
}

impl ArrayOfRelatedEntriesInner {
  pub fn new(id: String, text: String) -> ArrayOfRelatedEntriesInner {
    ArrayOfRelatedEntriesInner {
      domains: None,
      id: id,
      language: None,
      regions: None,
      registers: None,
      text: text,
    }
  }

  pub fn set_domains(&mut self, domains: Vec<String>) {
    self.domains = Some(domains);
  }

  pub fn with_domains(mut self, domains: Vec<String>) -> ArrayOfRelatedEntriesInner {
    self.domains = Some(domains);
    self
  }

  pub fn domains(&self) -> Option<&Vec<String>> {
    self.domains.as_ref()
  }

  pub fn reset_domains(&mut self) {
    self.domains = None;
  }

  pub fn set_id(&mut self, id: String) {
    self.id = id;
  }

  pub fn with_id(mut self, id: String) -> ArrayOfRelatedEntriesInner {
    self.id = id;
    self
  }

  pub fn id(&self) -> &String {
    &self.id
  }

  pub fn set_language(&mut self, language: String) {
    self.language = Some(language);
  }

  pub fn with_language(mut self, language: String) -> ArrayOfRelatedEntriesInner {
    self.language = Some(language);
    self
  }

  pub fn language(&self) -> Option<&String> {
    self.language.as_ref()
  }

  pub fn reset_language(&mut self) {
    self.language = None;
  }

  pub fn set_regions(&mut self, regions: Vec<String>) {
    self.regions = Some(regions);
  }

  pub fn with_regions(mut self, regions: Vec<String>) -> ArrayOfRelatedEntriesInner {
    self.regions = Some(regions);
    self
  }

  pub fn regions(&self) -> Option<&Vec<String>> {
    self.regions.as_ref()
  }

  pub fn reset_regions(&mut self) {
    self.regions = None;
  }

  pub fn set_registers(&mut self, registers: Vec<String>) {
    self.registers = Some(registers);
  }

  pub fn with_registers(mut self, registers: Vec<String>) -> ArrayOfRelatedEntriesInner {
    self.registers = Some(registers);
    self
  }

  pub fn registers(&self) -> Option<&Vec<String>> {
    self.registers.as_ref()
  }

  pub fn reset_registers(&mut self) {
    self.registers = None;
  }

  pub fn set_text(&mut self, text: String) {
    self.text = text;
  }

  pub fn with_text(mut self, text: String) -> ArrayOfRelatedEntriesInner {
    self.text = text;
    self
  }

  pub fn text(&self) -> &String {
    &self.text
  }
}
