/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ArrayOfRelatedEntries : A list of written or spoken words

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ArrayOfRelatedEntries {}

impl ArrayOfRelatedEntries {
  /// A list of written or spoken words
  pub fn new() -> ArrayOfRelatedEntries {
    ArrayOfRelatedEntries {}
  }
}
