/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CategorizedTextList : various types of notes that appear

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CategorizedTextList {}

impl CategorizedTextList {
  /// various types of notes that appear
  pub fn new() -> CategorizedTextList {
    CategorizedTextList {}
  }
}
