/* 
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CrossReferencesList : A reference to another word that is closely related, might provide additional information about the subject, has a variant spelling or is an abbreviated form of it.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CrossReferencesList {
}

impl CrossReferencesList {
  /// A reference to another word that is closely related, might provide additional information about the subject, has a variant spelling or is an abbreviated form of it.
  pub fn new() -> CrossReferencesList {
    CrossReferencesList {
    }
  }

}



