/* 
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ExamplesList : A list of written or spoken rendering of examples of use of a word or text

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ExamplesList {
}

impl ExamplesList {
  /// A list of written or spoken rendering of examples of use of a word or text
  pub fn new() -> ExamplesList {
    ExamplesList {
    }
  }

}



