/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GrammaticalFeaturesList : The different forms are correlated with meanings or functions which we text as 'features'

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GrammaticalFeaturesList {}

impl GrammaticalFeaturesList {
  /// The different forms are correlated with meanings or functions which we text as 'features'
  pub fn new() -> GrammaticalFeaturesList {
    GrammaticalFeaturesList {}
  }
}
