/* 
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// InflectionsList : A grouping of the modifications of a word to express different grammatical categories

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InflectionsList {
}

impl InflectionsList {
  /// A grouping of the modifications of a word to express different grammatical categories
  pub fn new() -> InflectionsList {
    InflectionsList {
    }
  }

}



