/* 
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Languages : Schema for the languages endpoint.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Languages {
  /// Additional Information provided by OUP
  #[serde(rename = "metadata")]
  metadata: Option<Value>,
  /// A list of languages available.
  #[serde(rename = "results")]
  results: Option<Vec<::models::LanguagesResults>>
}

impl Languages {
  /// Schema for the languages endpoint.
  pub fn new() -> Languages {
    Languages {
      metadata: None,
      results: None
    }
  }

  pub fn set_metadata(&mut self, metadata: Value) {
    self.metadata = Some(metadata);
  }

  pub fn with_metadata(mut self, metadata: Value) -> Languages {
    self.metadata = Some(metadata);
    self
  }

  pub fn metadata(&self) -> Option<&Value> {
    self.metadata.as_ref()
  }

  pub fn reset_metadata(&mut self) {
    self.metadata = None;
  }

  pub fn set_results(&mut self, results: Vec<::models::LanguagesResults>) {
    self.results = Some(results);
  }

  pub fn with_results(mut self, results: Vec<::models::LanguagesResults>) -> Languages {
    self.results = Some(results);
    self
  }

  pub fn results(&self) -> Option<&Vec<::models::LanguagesResults>> {
    self.results.as_ref()
  }

  pub fn reset_results(&mut self) {
    self.results = None;
  }

}



