/* 
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// LanguagesTargetLanguage : Translation language of the results

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct LanguagesTargetLanguage {
  /// IANA language code
  #[serde(rename = "id")]
  id: Option<String>,
  /// Language label.
  #[serde(rename = "language")]
  language: Option<String>
}

impl LanguagesTargetLanguage {
  /// Translation language of the results
  pub fn new() -> LanguagesTargetLanguage {
    LanguagesTargetLanguage {
      id: None,
      language: None
    }
  }

  pub fn set_id(&mut self, id: String) {
    self.id = Some(id);
  }

  pub fn with_id(mut self, id: String) -> LanguagesTargetLanguage {
    self.id = Some(id);
    self
  }

  pub fn id(&self) -> Option<&String> {
    self.id.as_ref()
  }

  pub fn reset_id(&mut self) {
    self.id = None;
  }

  pub fn set_language(&mut self, language: String) {
    self.language = Some(language);
  }

  pub fn with_language(mut self, language: String) -> LanguagesTargetLanguage {
    self.language = Some(language);
    self
  }

  pub fn language(&self) -> Option<&String> {
    self.language.as_ref()
  }

  pub fn reset_language(&mut self) {
    self.language = None;
  }

}



