/* 
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// PronunciationsList : A list of possible pronunciations of a word

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PronunciationsList {
}

impl PronunciationsList {
  /// A list of possible pronunciations of a word
  pub fn new() -> PronunciationsList {
    PronunciationsList {
    }
  }

}



