/* 
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ThesaurusLink : Link to a sense of a specific entry in the thesaurus Dictionary

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ThesaurusLink {
  /// identifier of a word
  #[serde(rename = "entry_id")]
  entry_id: String,
  /// identifier of a sense
  #[serde(rename = "sense_id")]
  sense_id: String
}

impl ThesaurusLink {
  /// Link to a sense of a specific entry in the thesaurus Dictionary
  pub fn new(entry_id: String, sense_id: String) -> ThesaurusLink {
    ThesaurusLink {
      entry_id: entry_id,
      sense_id: sense_id
    }
  }

  pub fn set_entry_id(&mut self, entry_id: String) {
    self.entry_id = entry_id;
  }

  pub fn with_entry_id(mut self, entry_id: String) -> ThesaurusLink {
    self.entry_id = entry_id;
    self
  }

  pub fn entry_id(&self) -> &String {
    &self.entry_id
  }


  pub fn set_sense_id(&mut self, sense_id: String) {
    self.sense_id = sense_id;
  }

  pub fn with_sense_id(mut self, sense_id: String) -> ThesaurusLink {
    self.sense_id = sense_id;
    self
  }

  pub fn sense_id(&self) -> &String {
    &self.sense_id
  }


}



