/* 
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// TranslationsList : A list of written or spoken rendering of the meaning of a word or text in another language(s)

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TranslationsList {
}

impl TranslationsList {
  /// A list of written or spoken rendering of the meaning of a word or text in another language(s)
  pub fn new() -> TranslationsList {
    TranslationsList {
    }
  }

}



