/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TranslationsListInner {
  /// A subject, discipline, or branch of knowledge particular to the translation
  #[serde(rename = "domains")]
  domains: Option<Vec<String>>,
  #[serde(rename = "grammaticalFeatures")]
  grammatical_features: Option<Vec<::models::GrammaticalFeaturesListInner>>,
  /// IANA language code specifying the language of the translation
  #[serde(rename = "language")]
  language: String,
  #[serde(rename = "notes")]
  notes: Option<::models::CategorizedTextList>,
  /// A particular area in which the translation occurs, e.g. 'Great Britain'
  #[serde(rename = "regions")]
  regions: Option<Vec<String>>,
  /// A level of language usage, typically with respect to formality. e.g. 'offensive', 'informal'
  #[serde(rename = "registers")]
  registers: Option<Vec<String>>,
  #[serde(rename = "text")]
  text: String,
}

impl TranslationsListInner {
  pub fn new(language: String, text: String) -> TranslationsListInner {
    TranslationsListInner {
      domains: None,
      grammatical_features: None,
      language: language,
      notes: None,
      regions: None,
      registers: None,
      text: text,
    }
  }

  pub fn set_domains(&mut self, domains: Vec<String>) {
    self.domains = Some(domains);
  }

  pub fn with_domains(mut self, domains: Vec<String>) -> TranslationsListInner {
    self.domains = Some(domains);
    self
  }

  pub fn domains(&self) -> Option<&Vec<String>> {
    self.domains.as_ref()
  }

  pub fn reset_domains(&mut self) {
    self.domains = None;
  }

  pub fn set_grammatical_features(
    &mut self,
    grammatical_features: Vec<::models::GrammaticalFeaturesListInner>,
  ) {
    self.grammatical_features = Some(grammatical_features);
  }

  pub fn with_grammatical_features(
    mut self,
    grammatical_features: Vec<::models::GrammaticalFeaturesListInner>,
  ) -> TranslationsListInner {
    self.grammatical_features = Some(grammatical_features);
    self
  }

  pub fn grammatical_features(&self) -> Option<&Vec<::models::GrammaticalFeaturesListInner>> {
    self.grammatical_features.as_ref()
  }

  pub fn reset_grammatical_features(&mut self) {
    self.grammatical_features = None;
  }

  pub fn set_language(&mut self, language: String) {
    self.language = language;
  }

  pub fn with_language(mut self, language: String) -> TranslationsListInner {
    self.language = language;
    self
  }

  pub fn language(&self) -> &String {
    &self.language
  }

  pub fn set_notes(&mut self, notes: ::models::CategorizedTextList) {
    self.notes = Some(notes);
  }

  pub fn with_notes(mut self, notes: ::models::CategorizedTextList) -> TranslationsListInner {
    self.notes = Some(notes);
    self
  }

  pub fn notes(&self) -> Option<&::models::CategorizedTextList> {
    self.notes.as_ref()
  }

  pub fn reset_notes(&mut self) {
    self.notes = None;
  }

  pub fn set_regions(&mut self, regions: Vec<String>) {
    self.regions = Some(regions);
  }

  pub fn with_regions(mut self, regions: Vec<String>) -> TranslationsListInner {
    self.regions = Some(regions);
    self
  }

  pub fn regions(&self) -> Option<&Vec<String>> {
    self.regions.as_ref()
  }

  pub fn reset_regions(&mut self) {
    self.regions = None;
  }

  pub fn set_registers(&mut self, registers: Vec<String>) {
    self.registers = Some(registers);
  }

  pub fn with_registers(mut self, registers: Vec<String>) -> TranslationsListInner {
    self.registers = Some(registers);
    self
  }

  pub fn registers(&self) -> Option<&Vec<String>> {
    self.registers.as_ref()
  }

  pub fn reset_registers(&mut self) {
    self.registers = None;
  }

  pub fn set_text(&mut self, text: String) {
    self.text = text;
  }

  pub fn with_text(mut self, text: String) -> TranslationsListInner {
    self.text = text;
    self
  }

  pub fn text(&self) -> &String {
    &self.text
  }
}
