/* 
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// VariantFormsList : Various words that are used interchangeably depending on the context, e.g 'aluminium' and 'aluminum'

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct VariantFormsList {
}

impl VariantFormsList {
  /// Various words that are used interchangeably depending on the context, e.g 'aluminium' and 'aluminum'
  pub fn new() -> VariantFormsList {
    VariantFormsList {
    }
  }

}



