/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct VariantFormsListInner {
  /// A particular area in which the variant form occurs, e.g. 'Great Britain'
  #[serde(rename = "regions")]
  regions: Option<Vec<String>>,
  #[serde(rename = "text")]
  text: String,
}

impl VariantFormsListInner {
  pub fn new(text: String) -> VariantFormsListInner {
    VariantFormsListInner {
      regions: None,
      text: text,
    }
  }

  pub fn set_regions(&mut self, regions: Vec<String>) {
    self.regions = Some(regions);
  }

  pub fn with_regions(mut self, regions: Vec<String>) -> VariantFormsListInner {
    self.regions = Some(regions);
    self
  }

  pub fn regions(&self) -> Option<&Vec<String>> {
    self.regions.as_ref()
  }

  pub fn reset_regions(&mut self) {
    self.regions = None;
  }

  pub fn set_text(&mut self, text: String) {
    self.text = text;
  }

  pub fn with_text(mut self, text: String) -> VariantFormsListInner {
    self.text = text;
    self
  }

  pub fn text(&self) -> &String {
    &self.text
  }
}
